import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Switch, Route } from "wouter";
import { queryClient } from "./lib/queryClient";
import { QueryClientProvider } from "@tanstack/react-query";
import { Toaster } from "@/components/ui/toaster";
import { TooltipProvider } from "@/components/ui/tooltip";
import ErrorBoundary from "@/components/ErrorBoundary";
import Dashboard from "@/pages/dashboard";
import TransferFunds from "@/pages/transfer-funds";
import ProfileSettings from "@/pages/profile-settings";
import SecuritySettings from "@/pages/security-settings";
import PinSettings from "@/pages/pin-settings";
import CreditCards from "@/pages/credit-cards";
import TransactionHistory from "@/pages/transaction-history";
import History from "@/pages/history";
import StatementsReports from "@/pages/statements-reports";
import InvestmentPortfolio from "@/pages/investment-portfolio";
import WealthManagement from "@/pages/wealth-management";
import SupportCenter from "@/pages/support-center";
import CustomerSupport from "@/pages/customer-support";
import BankingServices from "./pages/banking-services";
import DigitalWallet from "./pages/digital-wallet";
import MobilePay from "./pages/mobile-pay";
import SecurityCenter from "./pages/security-center";
import FindBranches from "./pages/find-branches";
import InternationalTransfer from "./pages/international-transfer";
import InvestmentTrading from "./pages/investment-trading";
import BusinessBanking from "./pages/business-banking";
import NotFound from "@/pages/not-found";
import Login from "@/pages/login";
import Register from "@/pages/register";
import MultiStepRegister from "@/pages/register-multi-step";
import AdminLogin from "@/pages/admin-login";
import AdminDashboard from "@/pages/admin-dashboard";
import SimpleAdmin from "@/pages/simple-admin";
import TransferProcessing from "@/pages/transfer-processing";
import TransferPending from "@/pages/transfer-pending";
import TransferSuccess from "@/pages/transfer-success";
import TransferFailed from "@/pages/transfer-failed";
import Transfer from "@/pages/transfer";
import Cards from "@/pages/cards";
import Receive from "@/pages/receive";
import AddMoney from "@/pages/add-money";
import Alerts from "@/pages/alerts";
import CustomerManagement from "@/pages/customer-management";
import FundManagement from "@/pages/fund-management";
import AdminLiveChat from "@/pages/admin-live-chat";
import CustomerServicePortal from "@/pages/customer-service-portal";
import VerificationCenter from "@/pages/verification";
import AccountPreferences from "@/pages/account-preferences";
import AdminTransactionDashboard from "@/pages/admin-transaction-dashboard";
import AdminTransactionCreator from "@/pages/admin-transaction-creator";
import TransactionRouter from "@/pages/transaction-router";
import About from "@/pages/about";
import Investment from "@/pages/investment";
import Exchange from "@/pages/exchange";
import { ProtectedRoute } from "@/components/ProtectedRoute";
import { AuthProvider } from "@/contexts/AuthContext";
import { LanguageProvider } from "@/contexts/LanguageContext";
import BottomNavigation from "@/components/BottomNavigation";
function App() {
    return (_jsx(ErrorBoundary, { children: _jsxs(QueryClientProvider, { client: queryClient, children: [_jsx(TooltipProvider, { children: _jsx(AuthProvider, { children: _jsx(LanguageProvider, { children: _jsx("div", { className: "min-h-screen bg-gradient-to-br from-slate-50 via-blue-50 to-indigo-100", children: _jsxs(Switch, { children: [_jsx(Route, { path: "/about", component: About }), _jsx(Route, { path: "/login", component: Login }), _jsx(Route, { path: "/register", component: Register }), _jsx(Route, { path: "/register-multi", component: MultiStepRegister }), _jsx(Route, { path: "/admin-login", component: AdminLogin }), _jsx(Route, { path: "/admin-dashboard", component: AdminDashboard }), _jsx(Route, { path: "/simple-admin", component: SimpleAdmin }), _jsx(Route, { path: "/admin-live-chat", component: AdminLiveChat }), _jsx(Route, { path: "/customer-service", component: CustomerServicePortal }), _jsx(Route, { path: "/transfer-processing", component: TransferProcessing }), _jsx(Route, { path: "/transfer-pending", component: TransferPending }), _jsx(Route, { path: "/transfer-success", component: TransferSuccess }), _jsx(Route, { path: "/transfer-failed", component: TransferFailed }), _jsx(Route, { path: "/", nest: true, children: _jsxs(ProtectedRoute, { children: [_jsx("div", { className: "pb-20", children: _jsxs(Switch, { children: [_jsx(Route, { path: "/", component: Dashboard }), _jsx(Route, { path: "/dashboard", component: Dashboard }), _jsx(Route, { path: "/transfer-funds", component: TransferFunds }), _jsx(Route, { path: "/profile-settings", component: ProfileSettings }), _jsx(Route, { path: "/security-settings", component: SecuritySettings }), _jsx(Route, { path: "/pin-settings", component: PinSettings }), _jsx(Route, { path: "/credit-cards", component: CreditCards }), _jsx(Route, { path: "/transaction-history", component: TransactionHistory }), _jsx(Route, { path: "/history", component: History }), _jsx(Route, { path: "/statements-reports", component: StatementsReports }), _jsx(Route, { path: "/investment-portfolio", component: InvestmentPortfolio }), _jsx(Route, { path: "/wealth-management", component: WealthManagement }), _jsx(Route, { path: "/support-center", component: SupportCenter }), _jsx(Route, { path: "/customer-support", component: CustomerSupport }), _jsx(Route, { path: "/banking-services", component: BankingServices }), _jsx(Route, { path: "/digital-wallet", component: DigitalWallet }), _jsx(Route, { path: "/mobile-pay", component: MobilePay }), _jsx(Route, { path: "/security-center", component: SecurityCenter }), _jsx(Route, { path: "/find-branches", component: FindBranches }), _jsx(Route, { path: "/international-transfer", component: InternationalTransfer }), _jsx(Route, { path: "/investment-trading", component: InvestmentTrading }), _jsx(Route, { path: "/business-banking", component: BusinessBanking }), _jsx(Route, { path: "/cards", component: Cards }), _jsx(Route, { path: "/transfer", component: Transfer }), _jsx(Route, { path: "/receive", component: Receive }), _jsx(Route, { path: "/add-money", component: AddMoney }), _jsx(Route, { path: "/alerts", component: Alerts }), _jsx(Route, { path: "/verification", component: VerificationCenter }), _jsx(Route, { path: "/account-preferences", component: AccountPreferences }), _jsx(Route, { path: "/admin-transaction-dashboard", component: AdminTransactionDashboard }), _jsx(Route, { path: "/admin-transaction-creator", component: AdminTransactionCreator }), _jsx(Route, { path: "/transaction-router", component: TransactionRouter }), _jsx(Route, { path: "/customer-management", component: CustomerManagement }), _jsx(Route, { path: "/fund-management", component: FundManagement }), _jsx(Route, { path: "/investment", component: Investment }), _jsx(Route, { path: "/exchange", component: Exchange }), _jsx(Route, { path: "/about", component: About }), _jsx(Route, { component: NotFound })] }) }), _jsx(BottomNavigation, {})] }) })] }) }) }) }) }), _jsx(Toaster, {})] }) }));
}
export default App;
