interface UserProfile {
    id: number;
    username: string;
    fullName: string;
    email: string;
    phone: string;
    accountNumber: string;
    accountId: string;
    profession: string;
    dateOfBirth: string;
    address: string;
    city: string;
    state: string;
    country: string;
    postalCode: string;
    nationality: string;
    annualIncome: string;
    idType: string;
    idNumber: string;
    transferPin: string;
    role: string;
    isVerified: boolean;
    isOnline: boolean;
    isActive: boolean;
    avatarUrl?: string;
    balance: number;
    createdAt: string;
}
export declare function useUserData(): import("@tanstack/react-query").UseQueryResult<UserProfile | null, Error>;
export declare function useAccountData(): import("@tanstack/react-query").UseQueryResult<any, Error>;
export {};
