import React, { createContext, useContext, useState } from 'react';

interface Language {
  code: string;
  name: string;
  flag: string;
}

interface LanguageContextType {
  currentLanguage: Language;
  setLanguage: (language: Language) => void;
  languages: Language[];
  t: (key: string) => string;
}

const languages: Language[] = [
  { code: 'en', name: 'English', flag: '🇺🇸' },
  { code: 'zh', name: '中文', flag: '🇨🇳' }
];

const translations: { [key: string]: { [key: string]: string } } = {
  en: {
    // Navigation & Menu
    'dashboard': 'Dashboard',
    'home': 'Home',
    'cards': 'Cards',
    'transfer': 'Transfer',
    'history': 'History',
    'profile': 'Profile',
    'logout': 'Logout',
    'nav_home': 'Home',
    'nav_cards': 'Cards',
    'nav_transfer': 'Transfer',
    'nav_history': 'History',
    'nav_profile': 'Profile',
    
    // Authentication
    'login': 'Login',
    'email_address': 'Email Address',
    'password': 'Password',
    'security_pin': 'Security PIN',
    'sign_in': 'Sign In',
    'signing_in': 'Signing In...',
    'pin_verification_required': 'PIN Verification Required',
    'enter_pin_complete_login': 'Please enter your 4-digit security PIN to complete login',
    'verify_pin': 'Verify PIN',
    'cancel': 'Cancel',
    'new_customer': 'New customer?',
    'create_account': 'Create an account',
    'demo_credentials': 'Demo Credentials',
    'login_successful': 'Login Successful',
    'welcome_to_bank': 'Welcome to World Bank!',
    'login_failed': 'Login Failed',
    'invalid_pin': 'Invalid PIN. Please try again.',
    
    // Dashboard & Welcome
    'welcome': 'Welcome',
    'good_morning': 'Good Morning',
    'good_afternoon': 'Good Afternoon', 
    'good_evening': 'Good Evening',
    'marine_engineer': 'Marine Engineer',
    'oil_rig_company': 'Oil Rig Company',
    'online': 'Online',
    'authenticated': 'Authenticated',
    'account_balance': 'Account Balance',
    'total_balance': 'Total Balance',
    'my_accounts': 'My Accounts',
    'account': 'Account',
    'account_number': 'Account Number',
    'account_id': 'Account ID',
    'hide_balance': 'Hide Balance',
    'show_balance': 'Show Balance',
    
    // Quick Actions
    'quick_actions': 'Quick Actions',
    'send_money': 'Send Money',
    'receive_money': 'Receive Money', 
    'add_money': 'Add Money',
    'alerts': 'Alerts',
    'transfer_funds_action': 'Transfer Funds',
    'request_money': 'Request Money',
    'deposit_funds': 'Deposit Funds',
    'notifications': 'Notifications',

    // Account Preferences
    'account_preferences': 'Account Preferences',
    'manage_account_settings': 'Manage your account settings and preferences',
    'notification_preferences': 'Notification Preferences',
    'email_notifications': 'Email Notifications',
    'sms_notifications': 'SMS Notifications', 
    'push_notifications': 'Push Notifications',
    'marketing_notifications': 'Marketing Communications',
    'privacy_settings': 'Privacy Settings',
    'share_data': 'Share Data with Partners',
    'two_factor_auth': 'Two-Factor Authentication',
    'display_preferences': 'Display Preferences',
    'preferred_currency': 'Preferred Currency',
    'language': 'Language',
    'theme': 'Theme',
    'security_settings': 'Security Settings',
    'notification_preferences': 'Notification Preferences',
    'session_timeout': 'Session Timeout (minutes)',
    'biometric_auth': 'Biometric Authentication',
    'auto_logout': 'Auto Logout',
    'save_preferences': 'Save Preferences',
    'preferences_saved': 'Preferences saved successfully',

    // Verification Center
    'verification_center': 'Verification Center',
    'manage_account_verification_status': 'Manage your account verification status',
    'account_security_level': 'Account Security Level',
    'fully_verified': 'Fully Verified',
    'total_verifications': 'Total Verifications',
    'verified': 'Verified',
    'pending': 'Pending',
    'action_required': 'Action Required',
    'all_verifications': 'All Verifications',
    'required': 'Required',
    'identity_verification': 'Identity Verification',
    'government_issued_id_verification': 'Government-issued ID verification',
    'submitted_documents': 'Submitted Documents',
    'last_updated': 'Last Updated',
    'under_review': 'Under Review',
    'email_verification': 'Email Verification',
    'confirm_email_address': 'Confirm your email address',
    'phone_verification': 'Phone Verification', 
    'verify_mobile_number': 'Verify your mobile number',
    'address_verification': 'Address Verification',
    'proof_of_residence_verification': 'Proof of residence verification',
    'income_verification': 'Income Verification',
    'employment_and_income_proof': 'Employment and income proof',
    'enhanced_due_diligence': 'Enhanced Due Diligence',
    'additional_verification_high_value': 'Additional verification for high-value transactions',
    'biometric_verification': 'Biometric Verification',
    'facial_recognition_fingerprint': 'Facial recognition and fingerprint',
    'tax_compliance': 'Tax Compliance',
    'tax_residency_status': 'Tax residency status verification',
    'upload_documents': 'Upload Documents',
    'regulatory_compliance': 'Regulatory Compliance',
    'verification_compliance_description': 'Our verification process ensures compliance with international banking regulations and provides enhanced security for your financial transactions.',
    'know_your_customer_kyc': 'Know Your Customer (KYC) compliance',
    'anti_money_laundering_aml': 'Anti-Money Laundering (AML) regulations',
    'combating_financing_terrorism_cft': 'Combating the Financing of Terrorism (CFT)',
    'international_banking_regulations': 'International banking regulations and standards',
    
    // Universal Terms
    'loading': 'Loading...',
    'learn_more': 'Learn More',
    'submit': 'Submit',
    'continue': 'Continue',
    'back': 'Back',
    'next': 'Next',
    'close': 'Close',
    'open': 'Open',
    'save': 'Save',
    'delete': 'Delete',
    'edit': 'Edit',
    'view': 'View',
    'show': 'Show',
    'hide': 'Hide',
    'send': 'Send',
    'receive': 'Receive',
    'hello': 'Hello',
    'thank_you': 'Thank you',
    'please': 'Please',
    'error': 'Error',
    'success': 'Success',
    'warning': 'Warning',
    'info': 'Info',
    'complete': 'Complete',
    'active': 'Active',
    'inactive': 'Inactive',
    'approved': 'Approved',
    'rejected': 'Rejected',
    'processing': 'Processing',
    'failed': 'Failed',
    'completed': 'Completed',
    
    // Footer & Legal Terms
    'security_center': 'Security Center',
    'privacy_policy': 'Privacy Policy',
    'contact_support': 'Contact Support',
    'copyright_notice': '© 2025 World Bank. All rights reserved.',
    'secure_trusted_global': 'Secure • Trusted • Global Banking Solutions',
    'licensed_regulated': 'Licensed and regulated worldwide',
    
    // Transfer & Transactions
    'international_transfer': 'International Transfer',
    'international_transfer_title': 'International Transfer',
    'international_transfer_desc': 'Send money worldwide securely',
    'domestic_transfer_title': 'Domestic Transfer',
    'domestic_transfer_desc': 'Transfer within your country',
    'card_transfer_title': 'Card to Card',
    'card_transfer_desc': 'Instant debit card transfers',
    'mobile_money_title': 'Mobile Money',
    'mobile_money_desc': 'Digital wallet transfers',
    'same_day': 'Same day',
    'instant': 'Instant',
    'minutes_to_hours': '15 mins - 2 hours',
    'international_banking': 'International Banking',
    'transfer_money': 'Transfer Money',
    'amount': 'Amount',
    'recipient': 'Recipient',
    'recipient_name': 'Recipient Name',
    'bank_details': 'Bank Details',
    'transfer_type': 'Transfer Type',
    'domestic': 'Domestic',
    'international': 'International',
    'send_transfer': 'Send Transfer',
    'transfer_processing': 'Transfer Processing',
    'compliance_review': 'Compliance review in progress',
    'reference_number': 'Reference Number',
    'estimated_time': 'Estimated Time',
    'business_days': '1-3 business days',
    'new_transfer': 'New Transfer',
    'track_transfer': 'Track Transfer',
    'recent_transactions': 'Recent Transactions',
    'recent_activity': 'Recent Activity',
    'view_all': 'View All',
    'no_transactions': 'No recent transactions',
    
    // Customer Service & Chat
    'customer_service': 'Customer Service',
    'live_chat': 'Live Chat',
    'chat_with_support': 'Chat with Support',
    'connected': 'Connected',
    'connecting': 'Connecting...',
    'disconnected': 'Disconnected',
    'type_message': 'Type your message...',
    'send_message': 'Send Message',
    'unread_messages': 'unread messages',
    'online_support': 'Online Support',
    'message_sent': 'Message sent',
    'typing': 'typing...',
    
    // Account Management
    'account_management': 'Account Management',
    'account_settings': 'Account Settings',
    'linked_accounts': 'Linked Accounts',
    
    // Banking Services
    'banking_services': 'Banking Services',
    'loans_credit': 'Loans & Credit',
    'investments': 'Investments',
    'insurance': 'Insurance',
    'credit_cards': 'Credit Cards',
    
    // Support & Help
    'support_help': 'Support & Help',
    'faq': 'FAQ',
    'contact_us': 'Contact Us',
    'support': 'Support',
    
    // Banking Services Content
    'checking_accounts': 'Checking Accounts',
    'checking_description': 'Full-service checking with global access',
    'no_minimum_balance': 'No minimum balance',
    'free_atm_worldwide': 'Free ATM worldwide',
    'mobile_banking': 'Mobile banking',
    'savings_accounts': 'Savings Accounts',
    'savings_description': 'High-yield savings with competitive rates',
    'high_apy': '2.5% APY',
    'no_monthly_fees': 'No monthly fees',
    'automatic_savings': 'Automatic savings plans',
    'credit_cards_description': 'Premium cards with global rewards',
    'no_foreign_fees': 'No foreign transaction fees',
    'travel_rewards': 'Travel rewards',
    'purchase_protection': 'Purchase protection',
    'mortgage_services': 'Mortgage Services',
    'mortgage_description': 'Home financing solutions worldwide',
    'competitive_rates': 'Competitive rates',
    'multiple_currencies': 'Multiple currencies',
    'expert_guidance': 'Expert guidance',
    
    // Brand & Platform Text
    'world_bank': 'WORLD BANK',
    'international_banking_solutions': 'International Banking Solutions',
    
    // Business Services
    'business_banking': 'Business Banking',
    'business_banking_description': 'Comprehensive solutions for businesses of all sizes',
    'multi_currency_accounts': 'Multi-currency accounts',
    'trade_finance': 'Trade finance',
    'cash_management': 'Cash management',
    'international_trade': 'International Trade',
    'international_trade_description': 'Global trade financing and services',
    'letters_of_credit': 'Letters of credit',
    'documentary_collections': 'Documentary collections',
    'trade_guarantees': 'Trade guarantees',
    'investment_services': 'Investment Services',
    'investment_services_description': 'Professional investment management',
    'portfolio_management': 'Portfolio management',
    'market_research': 'Market research',
    'risk_assessment': 'Risk assessment',
    'treasury_services': 'Treasury Services',
    'treasury_services_description': 'Corporate treasury and cash management',
    'liquidity_management': 'Liquidity management',
    'fx_services': 'FX services',
    'payment_solutions': 'Payment solutions',
    
    // Loan & Financing Services
    'loan_services': 'Loan Services',
    'loan_services_description': 'Personal and business lending solutions',
    'personal_loans': 'Personal loans',
    'auto_loans': 'Auto loans',
    'business_loans': 'Business loans',
    'equipment_financing': 'Equipment financing',
    'education_financing': 'Education Financing',
    'education_financing_description': 'Student loans and education planning',
    'student_loans': 'Student loans',
    'education_savings': 'Education savings',
    'study_abroad_financing': 'Study abroad financing',
    'insurance_services': 'Insurance Services',
    'insurance_services_description': 'Comprehensive protection solutions',
    'life_insurance': 'Life insurance',
    'property_insurance': 'Property insurance',
    'business_insurance': 'Business insurance',
    
    // User Profile Information
    'mr_liu_wei': 'Mr. Liu Wei',
    'liu_wei_name': 'Liu Wei',
    'marine_engineer_profession': 'Marine Engineer',
    'oil_rig_company_name': 'Oil Rig Company',
    'user_email': 'liu.wei@oilrig.com',
    'english_language': 'English',
    'chinese_language': 'Chinese',
    'verified_account': 'Verified Account',
    
    // Missing translation keys
    'personal_banking': 'Personal Banking',
    'help_center': 'Help Center',
    'connect': 'Connect',
    'copyright': 'Copyright',
    'terms_of_service': 'Terms of Service',
    
    // PIN Settings
    'change_transfer_pin': 'Change Transfer PIN',
    'current_pin': 'Current PIN',
    'new_pin': 'New PIN',
    'confirm_new_pin': 'Confirm New PIN',
    'enter_current_pin': 'Enter current PIN',
    'enter_new_pin': 'Enter new PIN',
    'pin_security_description': 'Manage your transfer PIN for secure transactions and account access.',
    'pin_must_be_4_digits': 'PIN must be 4 digits',
    'pin_must_be_numeric': 'PIN must contain only numbers',
    'pin_cannot_be_repeated': 'PIN cannot have all same digits',
    'pin_too_simple': 'PIN is too simple. Avoid common patterns.',
    'pins_do_not_match': 'PINs do not match',
    'new_pin_must_be_different': 'New PIN must be different from current PIN',
    'all_fields_required': 'All fields are required',
    'pin_changed_successfully': 'PIN changed successfully',
    'pin_change_failed': 'Failed to change PIN',
    'network_error': 'Network error. Please try again.',
    'changing_pin': 'Changing PIN...',
    'change_pin': 'Change PIN',
    'confirm_pin_change': 'Confirm PIN Change',
    'pin_change_confirmation_message': 'Are you sure you want to change your transfer PIN? This will affect all future transactions.',
    'confirm_change': 'Confirm Change',
    'pin_too_short': 'PIN too short',
    'pin_weak': 'Weak',
    'pin_fair': 'Fair', 
    'pin_strong': 'Strong',
    'pin_security_tips': 'Security Tips',
    'pin_tip_1': 'Use 4 unique digits',
    'pin_tip_2': 'Avoid sequential numbers (1234)',
    'pin_tip_3': 'Avoid repeated digits (1111)',
    'pin_tip_4': 'Keep your PIN confidential'
  },
  zh: {
    // Navigation & Menu
    'dashboard': '仪表板',
    'home': '首页',
    'cards': '卡片',
    'transfer': '转账',
    'history': '历史',
    'profile': '个人资料',
    'logout': '登出',
    'nav_home': '首页',
    'nav_cards': '卡片',
    'nav_transfer': '转账',
    'nav_history': '历史',
    'nav_profile': '个人资料',
    
    // Authentication
    'login': '登录',
    'email_address': '电子邮件地址',
    'password': '密码',
    'security_pin': '安全PIN码',
    'sign_in': '登录',
    'signing_in': '登录中...',
    'pin_verification_required': '需要PIN验证',
    'enter_pin_complete_login': '请输入您的4位安全PIN码以完成登录',
    'verify_pin': '验证PIN',
    'cancel': '取消',
    'new_customer': '新客户？',
    'create_account': '创建账户',
    'demo_credentials': '演示凭据',
    'login_successful': '登录成功',
    'welcome_to_bank': '欢迎来到世界银行！',
    'login_failed': '登录失败',
    'invalid_pin': '无效的PIN码。请重试。',
    
    // Dashboard & Welcome
    'welcome': '欢迎',
    'good_morning': '早上好',
    'good_afternoon': '下午好',
    'good_evening': '晚上好',
    'marine_engineer': '海洋工程师',
    'oil_rig_company': '石油钻井公司',
    'online': '在线',
    'authenticated': '已认证',
    'account_balance': '账户余额',
    'total_balance': '总余额',
    'my_accounts': '我的账户',
    'account': '账户',
    'account_number': '账户号码',
    'account_id': '账户ID',
    'hide_balance': '隐藏余额',
    'show_balance': '显示余额',
    
    // Quick Actions
    'quick_actions': '快速操作',
    'send_money': '汇款',
    'receive_money': '收款',
    'add_money': '充值',
    'alerts': '警报',
    'transfer_funds_action': '资金转账',
    'request_money': '请求资金',
    'deposit_funds': '存款',
    'notifications': '通知',
    
    // Universal Terms
    'loading': '加载中...',
    'learn_more': '了解更多',
    'submit': '提交',
    'continue': '继续',
    'back': '返回',
    'next': '下一步',
    'close': '关闭',
    'open': '打开',
    'save': '保存',
    'delete': '删除',
    'edit': '编辑',
    'view': '查看',
    'show': '显示',
    'hide': '隐藏',
    'send': '发送',
    'receive': '接收',
    'hello': '您好',
    'thank_you': '谢谢您',
    'please': '请',
    'error': '错误',
    'success': '成功',
    'warning': '警告',
    'info': '信息',
    'complete': '完成',
    'pending': '待处理',
    'active': '激活',
    'inactive': '未激活',
    'approved': '已批准',
    'rejected': '已拒绝',
    'processing': '处理中',
    'failed': '失败',
    'completed': '已完成',
    
    // Footer & Legal Terms
    'security_center': '安全中心',
    'privacy_policy': '隐私政策',
    'contact_support': '联系支持',
    'copyright_notice': '© 2025 世界银行。版权所有。',
    'secure_trusted_global': '安全 • 可信 • 全球银行解决方案',
    'licensed_regulated': '全球许可和监管',
    
    // Transfer & Transactions
    'international_transfer': '国际转账',
    'international_transfer_title': '国际转账',
    'international_transfer_desc': '安全地向全世界汇款',
    'domestic_transfer_title': '国内转账',
    'domestic_transfer_desc': '在您的国家内转账',
    'card_transfer_title': '卡对卡',
    'card_transfer_desc': '即时借记卡转账',
    'mobile_money_title': '移动钱包',
    'mobile_money_desc': '数字钱包转账',
    'same_day': '当天',
    'instant': '即时',
    'minutes_to_hours': '15分钟 - 2小时',
    'international_banking': '国际银行业务',
    'transfer_money': '转账',
    'amount': '金额',
    'recipient': '收款人',
    'recipient_name': '收款人姓名',
    'bank_details': '银行详情',
    'transfer_type': '转账类型',
    'domestic': '国内',
    'international': '国际',
    'send_transfer': '发送转账',
    'transfer_processing': '转账处理中',
    'compliance_review': '合规审查进行中',
    'reference_number': '参考号码',
    'estimated_time': '预计时间',
    'business_days': '1-3个工作日',
    'new_transfer': '新转账',
    'track_transfer': '跟踪转账',
    'recent_transactions': '最近交易',
    'recent_activity': '最近活动',
    'view_all': '查看全部',
    'no_transactions': '没有最近的交易',
    
    // Customer Service & Chat
    'customer_service': '客户服务',
    'live_chat': '在线聊天',
    'chat_with_support': '与支持聊天',
    'connected': '已连接',
    'connecting': '连接中...',
    'disconnected': '已断开',
    'type_message': '输入您的消息...',
    'send_message': '发送消息',
    'unread_messages': '条未读消息',
    'online_support': '在线支持',
    'message_sent': '消息已发送',
    'typing': '正在输入...',
    
    // Account Management
    'account_management': '账户管理',
    'account_settings': '账户设置',
    'security_settings': '安全设置',
    'notification_preferences': '通知偏好',
    'linked_accounts': '关联账户',
    
    // Banking Services
    'banking_services': '银行服务',
    'loans_credit': '贷款和信贷',
    'investments': '投资',
    'insurance': '保险',
    'credit_cards': '信用卡',
    
    // Support & Help
    'support_help': '支持与帮助',
    'faq': '常见问题',
    'contact_us': '联系我们',
    'support': '支持',
    
    // Banking Services Content
    'checking_accounts': '支票账户',
    'checking_description': '全球访问全方位支票服务',
    'no_minimum_balance': '无最低余额要求',
    'free_atm_worldwide': '全球免费ATM',
    'mobile_banking': '手机银行',
    'savings_accounts': '储蓄账户',
    'savings_description': '高收益储蓄，竞争性利率',
    'high_apy': '2.5% 年利率',
    'no_monthly_fees': '无月费',
    'automatic_savings': '自动储蓄计划',
    'credit_cards_description': '全球奖励高端卡片',
    'no_foreign_fees': '无境外交易费',
    'travel_rewards': '旅行奖励',
    'purchase_protection': '购买保护',
    'mortgage_services': '抵押贷款服务',
    'mortgage_description': '全球房屋融资解决方案',
    'competitive_rates': '竞争性利率',
    'multiple_currencies': '多币种',
    'expert_guidance': '专家指导',
    
    // Brand & Platform Text
    'world_bank': '世界银行',
    'international_banking_solutions': '国际银行解决方案',
    
    // Business Services
    'business_banking': '企业银行',
    'business_banking_description': '为各种规模企业提供全面解决方案',
    'multi_currency_accounts': '多币种账户',
    'trade_finance': '贸易融资',
    'cash_management': '现金管理',
    'international_trade': '国际贸易',
    'international_trade_description': '全球贸易融资和服务',
    'letters_of_credit': '信用证',
    'documentary_collections': '跟单托收',
    'trade_guarantees': '贸易担保',
    'investment_services': '投资服务',
    'investment_services_description': '专业投资管理',
    'portfolio_management': '投资组合管理',
    'market_research': '市场研究',
    'risk_assessment': '风险评估',
    'treasury_services': '资金服务',
    'treasury_services_description': '企业资金和现金管理',
    'liquidity_management': '流动性管理',
    'fx_services': '外汇服务',
    'payment_solutions': '支付解决方案',
    
    // Loan & Financing Services
    'loan_services': '贷款服务',
    'loan_services_description': '个人和企业借贷解决方案',
    'personal_loans': '个人贷款',
    'auto_loans': '汽车贷款',
    'business_loans': '企业贷款',
    'equipment_financing': '设备融资',
    'education_financing': '教育融资',
    'education_financing_description': '学生贷款和教育规划',
    'student_loans': '学生贷款',
    'education_savings': '教育储蓄',
    'study_abroad_financing': '海外留学融资',
    'insurance_services': '保险服务',
    'insurance_services_description': '全面保护解决方案',
    'life_insurance': '人寿保险',
    'property_insurance': '财产保险',
    'business_insurance': '企业保险',
    
    // User Profile Information
    'mr_liu_wei': '刘伟先生',
    'liu_wei_name': '刘伟',
    'marine_engineer_profession': '海洋工程师',
    'oil_rig_company_name': '石油钻井公司',
    'user_email': 'liu.wei@oilrig.com',
    'english_language': '英语',
    'chinese_language': '中文',
    'verified_account': '已验证账户',
    
    // PIN Settings
    'change_transfer_pin': '更改转账密码',
    'current_pin': '当前密码',
    'new_pin': '新密码',
    'confirm_new_pin': '确认新密码',
    'enter_current_pin': '输入当前密码',
    'enter_new_pin': '输入新密码',
    'pin_security_description': '管理您的转账密码以确保交易和账户访问安全。',
    'pin_must_be_4_digits': '密码必须是4位数字',
    'pin_must_be_numeric': '密码只能包含数字',
    'pin_cannot_be_repeated': '密码不能是相同数字',
    'pin_too_simple': '密码过于简单，请避免常见模式。',
    'pins_do_not_match': '密码不匹配',
    'new_pin_must_be_different': '新密码必须与当前密码不同',
    'all_fields_required': '所有字段都是必需的',
    'pin_changed_successfully': '密码更改成功',
    'pin_change_failed': '密码更改失败',
    'network_error': '网络错误，请重试。',
    'changing_pin': '正在更改密码...',
    'change_pin': '更改密码',
    'confirm_pin_change': '确认密码更改',
    'pin_change_confirmation_message': '您确定要更改转账密码吗？这将影响所有未来交易。',
    'confirm_change': '确认更改',
    'pin_too_short': '密码太短',
    'pin_weak': '弱',
    'pin_fair': '一般',
    'pin_strong': '强',
    'pin_security_tips': '安全提示',
    'pin_tip_1': '使用4个不同的数字',
    'pin_tip_2': '避免连续数字（1234）',
    'pin_tip_3': '避免重复数字（1111）',
    'pin_tip_4': '保持密码机密',
    
    // Verification Center
    'verification_center': '验证中心',
    'manage_account_verification_status': '管理您的账户验证状态和合规要求',
    'identity_verification': '身份验证',
    'government_issued_id_verification': '政府签发身份证件验证以确保账户安全',
    'email_verification': '邮箱验证',
    'confirm_email_address': '确认您的邮箱地址以接收账户通知',
    'phone_verification': '手机验证',
    'verify_mobile_number': '验证您的手机号码以确保安全通信',
    'address_verification': '地址验证',
    'proof_of_residence_verification': '居住证明验证以符合合规要求',
    'income_verification': '收入验证',
    'employment_and_income_proof': '就业和收入证明以确定账户限额',
    'enhanced_due_diligence': '增强尽职调查',
    'additional_verification_high_value': '高价值交易的额外验证',
    'biometric_verification': '生物识别验证',
    'facial_recognition_fingerprint': '面部识别和指纹验证',
    'tax_compliance': '税务合规',
    'tax_residency_status': '税务居住状态和合规验证',
    'account_security_level': '账户安全级别',
    'fully_verified': '完全验证',
    'total_verifications': '总验证项目',
    'verified': '已验证',
    'action_required': '需要操作',
    'all_verifications': '所有验证',
    'submitted_documents': '已提交文件',
    'last_updated': '最后更新',
    'upload_documents': '上传文件',
    'under_review': '审核中',
    'upload_verification_documents': '上传验证文件',
    'drag_drop_files_here': '拖拽文件到这里',
    'or_click_to_browse': '或点击浏览',
    'select_files': '选择文件',
    'accepted_formats': '接受的格式',
    'max_file_size': '最大文件大小',
    'verification_cancel': '取消',
    'upload': '上传',
    'regulatory_compliance': '监管合规',
    'verification_compliance_description': '我们的验证过程确保符合国际银行法规和反洗钱要求。',
    'know_your_customer_kyc': '了解您的客户（KYC）要求',
    'anti_money_laundering_aml': '反洗钱（AML）合规',
    'combating_financing_terrorism_cft': '打击恐怖主义融资（CFT）',
    'international_banking_regulations': '国际银行法规合规',
    'expired': '已过期',

    // Account Preferences
    'account_preferences': '账户偏好设置',
    'manage_account_settings': '管理您的账户设置和偏好',
    'notification_preferences': '通知偏好',
    'email_notifications': '邮件通知',
    'sms_notifications': '短信通知', 
    'push_notifications': '推送通知',
    'marketing_notifications': '营销推广',
    'privacy_settings': '隐私设置',
    'share_data': '与合作伙伴共享数据',
    'two_factor_auth': '双重身份验证',
    'display_preferences': '显示偏好',
    'preferred_currency': '首选货币',
    'language': '语言',
    'theme': '主题',
    'security_settings': '安全设置',
    'session_timeout': '会话超时（分钟）',
    'biometric_auth': '生物识别认证',
    'auto_logout': '自动登出',
    'save_preferences': '保存偏好设置',
    'preferences_saved': '偏好设置已保存',

    // Missing translation keys
    'personal_banking': '个人银行业务',
    'help_center': '帮助中心', 
    'connect': '连接',
    'copyright': '版权',
    'terms_of_service': '服务条款'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [currentLanguage, setCurrentLanguage] = useState<Language>(languages[0]);

  const setLanguage = (language: Language) => {
    setCurrentLanguage(language);
    localStorage.setItem('preferred-language', language.code);
  };

  const t = (key: string): string => {
    const translation = translations[currentLanguage.code]?.[key];
    if (!translation) {
      // console.warn(`Missing translation for key: ${key} in language: ${currentLanguage.code}`);
      return key;
    }
    return translation;
  };

  React.useEffect(() => {
    const savedLanguage = localStorage.getItem('preferred-language');
    if (savedLanguage) {
      const language = languages.find(lang => lang.code === savedLanguage);
      if (language) {
        setCurrentLanguage(language);
      }
    }
  }, []);

  return (
    <LanguageContext.Provider value={{ currentLanguage, setLanguage, languages, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}