import React, { createContext, useContext, useState, useEffect } from 'react';

interface Language {
  code: string;
  name: string;
  flag: string;
}

interface LanguageContextType {
  currentLanguage: Language;
  setLanguage: (language: Language) => void;
  languages: Language[];
  t: (key: string) => string;
}

const languages: Language[] = [
  { code: 'en', name: 'English', flag: '🇺🇸' },
  { code: 'zh', name: '中文', flag: '🇨🇳' }
];

const translations: Record<string, Record<string, string>> = {
  en: {
    // Login Page
    'world_bank': 'WORLD BANK',
    'international_banking_solutions': 'International Banking Solutions',
    'sign_in': 'Sign In',
    'access_your_secure_banking_portal': 'Access your secure banking portal',
    'email_address': 'Email Address',
    'user_id_or_email': 'User ID or Email',
    'id_placeholder': 'Enter your ID or email',
    'password': 'Password',
    'login_failed': 'Login Failed',
    'login_successful': 'Login Successful',
    'welcome_back': 'Welcome back to World Bank',
    'invalid_pin': 'Invalid PIN. Please try again.',
    'verification_failed': 'Verification failed. Please try again.',
    'enter_pin': 'Enter PIN',
    'pin_verification': 'PIN Verification',
    'enter_4_digit_pin': 'Enter your 4-digit PIN to continue',
    'signing_in': 'Signing In...',
    'security_center': 'Security Center',
    'new_customer': 'New customer?',
    'create_account': 'Create Account',
    'enter_first_name': 'Enter your first name',
    'enter_last_name': 'Enter your last name',
    'registration_submitted': 'Registration Submitted',
    'admin_review_pending': 'Your registration is pending admin review',
    'admin_review_description': 'Your account will be activated after admin verification',
    'next_steps': 'Next Steps',
    'admin_review_process': 'Admin will review your information',
    
    // PIN Verification
    'pin_verification_required': 'PIN Verification Required',
    'enter_pin_complete_login': 'Enter your PIN to complete login',
    'security_pin': 'Security PIN',
    'verify_pin': 'Verify PIN',

    
    // Form Fields
    'enter_email': 'Enter your email address',
    'enter_phone': 'Enter your phone number',
    'enter_address': 'Enter your address',
    'enter_city': 'Enter your city',
    'enter_state': 'Enter your state/province',
    'enter_postal_code': 'Enter your postal code',
    'enter_profession': 'Enter your profession',
    'enter_id_number': 'Enter your ID number',
    'enter_password': 'Enter your password',
    
    // Countries
    'china': 'China',
    'united_states': 'United States',
    'united_kingdom': 'United Kingdom',
    'canada': 'Canada',
    'australia': 'Australia',
    'germany': 'Germany',
    'france': 'France',
    'japan': 'Japan',
    'other': 'Other',
    
    // Income Ranges
    'under_25k': 'Under $25,000',
    '25k_50k': '$25,000 - $50,000',
    '50k_75k': '$50,000 - $75,000',
    '75k_100k': '$75,000 - $100,000',
    '100k_150k': '$100,000 - $150,000',
    'over_150k': 'Over $150,000',
    
    // ID Types
    'national_id': 'National ID',
    'passport': 'Passport',
    'drivers_license': "Driver's License",
    'email_notification_sent': 'Email notification will be sent',
    'account_activation_follows': 'Account activation will follow',
    'return_to_login': 'Return to Login',
    'join_world_bank_today': 'Join World Bank Today',
    'personal_information': 'Personal Information',
    'privacy_policy': 'Privacy Policy',
    'contact_support': 'Contact Support',
    'copyright_notice': '© 2024 World Bank Group. All rights reserved.',
    'secure_trusted_global': 'Secure • Trusted • Global',
    'licensed_regulated': 'Licensed & Regulated Financial Institution',
    'international_transfer_desc': 'Send money to 190+ countries worldwide',
    'domestic_transfer_desc': 'Transfer within your country instantly',
    'card_transfer_desc': 'Transfer to debit/credit cards globally',
    'mobile_money_desc': 'Mobile money transfers in 50+ countries',
    'first_name': 'First Name',
    'last_name': 'Last Name',
    'date_of_birth': 'Date of Birth',
    'contact_information': 'Contact Information',
    'phone_number': 'Phone Number',
    'address_information': 'Address Information',
    'street_address': 'Street Address',
    'city': 'City',
    'state_province': 'State/Province',
    'postal_code': 'Postal Code',
    'country': 'Country',
    'select_country': 'Select Country',
    'professional_information': 'Professional Information',
    'profession': 'Profession',
    'annual_income': 'Annual Income',
    'select_income_range': 'Select Income Range',
    'identification': 'Identification',
    'id_type': 'ID Type',
    'select_id_type': 'Select ID Type',
    'id_number': 'ID Number',
    'account_security': 'Account Security',
    'confirm_password': 'Confirm Password',
    'confirm_your_password': 'Confirm Your Password',
    'already_have_account': 'Already have an account?',
    'sign_in_here': 'Sign in here',
    
    // Basic UI
    'welcome': 'Welcome',
    'login': 'Login',
    'register': 'Register',
    'logout': 'Logout',
    'home': 'Home',
    'dashboard': 'Dashboard',
    'settings': 'Settings',
    'profile': 'Profile',
    'save': 'Save',
    'cancel': 'Cancel',
    'edit': 'Edit',
    'delete': 'Delete',
    'close': 'Close',
    'continue': 'Continue',
    'back': 'Back',
    'next': 'Next',
    'submit': 'Submit',
    'confirm': 'Confirm',
    'yes': 'Yes',
    'no': 'No',
    'loading': 'Loading...',
    'error': 'Error',
    'success': 'Success',
    'warning': 'Warning',
    'info': 'Information',
    'search': 'Search',
    'filter': 'Filter',
    'sort': 'Sort',
    'view': 'View',
    'download': 'Download',
    'upload': 'Upload',
    'copy': 'Copy',
    'paste': 'Paste',
    'cut': 'Cut',
    'undo': 'Undo',
    'redo': 'Redo',
    'refresh': 'Refresh',
    'update': 'Update',
    'create': 'Create',
    'new': 'New',
    'open': 'Open',
    'select': 'Select',
    'choose': 'Choose',
    'browse': 'Browse',
    'clear': 'Clear',
    'reset': 'Reset',
    
    // Navigation
    'nav_home': 'Home',
    'nav_cards': 'Cards',
    'nav_transfer': 'Transfer',
    'nav_history': 'History',
    'nav_profile': 'Profile',
    
    // Account Preferences
    'account_preferences': 'Account Preferences',
    'manage_account_settings': 'Manage your account settings and preferences',
    'notification_preferences': 'Notification Preferences',
    'email_notifications': 'Email Notifications',
    'sms_notifications': 'SMS Notifications',
    'push_notifications': 'Push Notifications',
    'marketing_notifications': 'Marketing Communications',
    'privacy_settings': 'Privacy Settings',
    'share_data': 'Share Data with Partners',
    'two_factor_auth': 'Two-Factor Authentication',
    'display_preferences': 'Display Preferences',
    'preferred_currency': 'Preferred Currency',
    
    // PIN Management
    'change_transfer_pin': 'Change Transfer PIN',
    'pin_security_description': 'Manage your 4-digit transfer PIN for secure transactions',
    'current_pin': 'Current PIN',
    'enter_current_pin': 'Enter your current 4-digit PIN',
    'new_pin': 'New PIN',
    'enter_new_pin': 'Enter your new 4-digit PIN',
    'confirm_new_pin': 'Confirm New PIN',
    'pin_security_tips': 'PIN Security Tips',
    'pin_tip_1': 'Use a unique 4-digit combination',
    'pin_tip_2': 'Avoid sequential numbers (1234, 5678)',
    'pin_tip_3': 'Avoid repeated digits (1111, 2222)',
    'pin_tip_4': 'Keep your PIN confidential',
    'change_pin': 'Change PIN',
    'pin_too_short': 'PIN must be exactly 4 digits',
    'confirm_pin_change': 'Confirm PIN Change',
    'pin_change_confirmation_message': 'Are you sure you want to change your transfer PIN?',
    'confirm_change': 'Confirm Change',
    
    // Missing translations
    'personal_banking': 'Personal Banking',
    'investment_services': 'Investment Services', 
    'copyright': 'Copyright',
    'terms_of_service': 'Terms of Service',
    'my_cards': 'My Cards',
    'manage_cards': 'Manage your credit and debit cards',
    'add_card': 'Add Card',
    'view_details': 'View Details',
    'manage': 'Manage',
    'instant_payments': 'Instant Payments',
    'instant_payments_desc': 'Make instant payments worldwide',
    'secure_transactions': 'Secure Transactions',
    'secure_transactions_desc': 'Bank-grade security for all transactions',
    'mobile_wallet': 'Mobile Wallet',
    'mobile_wallet_desc': 'Use your phone for contactless payments',
    'hide_balances': 'Hide Balances',
    'show_balances': 'Show Balances',
    'lock_card': 'Lock Card',
    'unlock_card': 'Unlock Card',
    'mobile_pay': 'Mobile Pay',
    'pay_bill': 'Pay Bill',
    'card_locked': 'Card Locked',
    'card_unlocked': 'Card Unlocked',
    'card_locked_desc': 'Your card has been locked for security',
    'card_unlocked_desc': 'Your card has been unlocked successfully',
    'lock_card_desc': 'Enter your PIN to lock this card for security',
    'unlock_card_desc': 'Enter your PIN to unlock this card for transactions',
    'mobile_payment_sent': 'Mobile Payment Sent',
    'bill_payment_successful': 'Bill Payment Successful',
    'settings_updated': 'Settings Updated',
    'card_settings_updated': 'Your card settings have been updated successfully',
    'unlock': 'Unlock',
    'lock': 'Lock',
    'phone_number': 'Phone Number',
    'send_payment': 'Send Payment',
    'bill_provider': 'Bill Provider',
    'pay_now': 'Pay Now',
    'card_settings': 'Card Settings',
    'daily_spending_limit': 'Daily Spending Limit',
    'contactless_payments': 'Contactless Payments',
    'card_status': 'Card Status',
    'enabled': 'Enabled',
    'disabled': 'Disabled',
    'locked': 'Locked',
    'active': 'Active',
    'save_changes': 'Save Changes',
    'sent': 'Sent',
    'to': 'to',
    'paid': 'Paid',
    'payment_failed': 'Payment failed. Please try again.',
    'operation_failed': 'Operation failed. Please try again.',
    
    'language': 'Language',
    'theme': 'Theme',
    'security_settings': 'Security Settings',
    'session_timeout': 'Session Timeout (minutes)',
    'biometric_auth': 'Biometric Authentication',
    'auto_logout': 'Auto Logout',
    'save_preferences': 'Save Preferences',
    
    // Verification Center
    'verification_center': 'Verification Center',
    'manage_account_verification_status': 'Manage your account verification status and compliance requirements',
    'identity_verification': 'Identity Verification',
    'verify_government_id': 'Verify your government-issued ID',
    'email_verification': 'Email Verification',
    'confirm_email_address': 'Confirm your email address',
    'phone_verification': 'Phone Verification',
    'verify_phone_number': 'Verify your phone number',
    'address_verification': 'Address Verification',
    'confirm_residential_address': 'Confirm your residential address',
    'income_verification': 'Income Verification',
    'verify_income_employment': 'Verify your income and employment status',
    'enhanced_due_diligence': 'Enhanced Due Diligence',
    'additional_verification_high_value': 'Additional verification for high-value transactions',
    'biometric_verification': 'Biometric Verification',
    'fingerprint_facial_recognition': 'Fingerprint and facial recognition setup',
    'tax_compliance': 'Tax Compliance',
    'tax_residency_status': 'Tax residency status and compliance verification',
    'account_security_level': 'Account Security Level',
    'fully_verified': 'Fully Verified',
    'total_verifications': 'Total Verifications',
    'verified': 'Verified',
    'pending': 'Pending',
    'required': 'Required',
    'action_required': 'Action Required',
    'all_verifications': 'All Verifications',
    'submitted_documents': 'Submitted Documents',
    'last_updated': 'Last Updated',
    'upload_documents': 'Upload Documents',
    'under_review': 'Under Review',
    'upload_verification_documents': 'Upload Verification Documents',
    'drag_drop_files_here': 'Drag and drop files here',
    'or_click_to_browse': 'or click to browse',
    'select_files': 'Select Files',
    'accepted_formats': 'Accepted Formats',
    'max_file_size': 'Max File Size',
    
    // Banking
    'balance': 'Balance',
    'account': 'Account',
    'transaction': 'Transaction',
    'transfer': 'Transfer',
    'send_money': 'Send Money',
    'receive_money': 'Receive Money',
    'cards': 'Cards',
    'history': 'History',
    'statements': 'Statements',
    'deposits': 'Deposits',
    'withdrawals': 'Withdrawals',
    'payments': 'Payments',
    'bills': 'Bills',
    'loans': 'Loans',
    'services': 'Services',
    
    // Account Management
    'account_management': 'Account Management',
    'account_settings': 'Account Settings',
    'linked_accounts': 'Linked Accounts',
    
    // Banking Services
    'banking_services': 'Banking Services',
    'loans_credit': 'Loans & Credit',
    'foreign_exchange': 'Foreign Exchange',
    'business_banking': 'Business Banking',
    'wealth_management': 'Wealth Management',
    'international_banking': 'International Banking',
    'trade_finance': 'Trade Finance',
    'cash_management': 'Cash Management',
    
    // Investment & Wealth
    'investment_wealth': 'Investment & Wealth',
    'portfolio_management': 'Portfolio Management',
    'retirement_planning': 'Retirement Planning',
    'financial_advisory': 'Financial Advisory',
    'market_research': 'Market Research',
    'investment_products': 'Investment Products',
    
    // Digital Services
    'digital_services': 'Digital Services',
    'mobile_banking': 'Mobile Banking',
    'online_banking': 'Online Banking',
    'digital_wallet': 'Digital Wallet',
    'contactless_payments': 'Contactless Payments',
    'biometric_login': 'Biometric Login',
    
    // Support & Help
    'support_help': 'Support & Help',
    'customer_service': 'Customer Service',
    'live_chat': 'Live Chat',
    'help_center': 'Help Center',
    'faqs': 'FAQs',
    'contact_us': 'Contact Us',
    'feedback': 'Feedback',
    'complaints': 'Complaints',
    
    // Status
    'active': 'Active',
    'inactive': 'Inactive',
    'approved': 'Approved',
    'rejected': 'Rejected',
    
    // Transfer Process
    'verify_transfer_pin': 'Verify Transfer PIN',
    'enter_4_digit_pin_to_authorize': 'Enter your 4-digit PIN to authorize this transfer',
    'transfer_pin': 'Transfer PIN',
    'verify_and_continue': 'Verify & Continue',
    'processing_transfer': 'Processing Transfer',
    'please_wait_processing': 'Please wait while we process your transfer...',
    'transaction_id': 'Transaction ID',

    'transfer_failed_try_again': 'Transfer failed. Please try again.',
    'processing_your_transfer_request': 'Processing your transfer request...',
    'transfer_pending': 'Transfer Pending',
    'transfer_submitted_for_review': 'Your transfer has been submitted for review',
    'awaiting_processing': 'Awaiting Processing',
    'transfer_id': 'Transfer ID',
    'amount': 'Amount',
    'recipient': 'Recipient',
    'bank': 'Bank',
    'admin_will_review_shortly': 'Our team will review and process your transfer shortly.',
    'return_to_dashboard': 'Return to Dashboard',
    'processing': 'Processing',
    'failed': 'Failed',
    'completed': 'Completed',
    
    // Quick Actions
    'quick_actions': 'Quick Actions',
    'add_money': 'Add Money',
    'alerts': 'Alerts',
    'notifications': 'Notifications',
    
    // Transfer Types
    'international_transfer': 'International Transfer',
    'domestic_transfer': 'Domestic Transfer',
    'card_transfer': 'Card Transfer',
    'mobile_money': 'Mobile Money',
    'international_transfer_title': 'Send money worldwide with competitive rates',
    'domestic_transfer_title': 'Fast transfers within your country',
    'card_transfer_title': 'Transfer directly to debit/credit cards',
    'mobile_money_title': 'Send to mobile wallets in 190+ countries',
    'same_day': 'Same day',
    'instant': 'Instant',
    'minutes_to_hours': '1-3 hours',
    
    // User Profile (Dynamic - loaded from API)
    'mr_liu_wei': 'Liu Wei',
    'marine_engineer': 'Marine Engineer', 
    'oil_rig_company': 'Oil Rig Company',
    'online': 'Online',
    'authenticated': 'Authenticated',
    
    // Timing
    'today': 'Today',
    'yesterday': 'Yesterday',
    'this_week': 'This Week',
    'this_month': 'This Month',
    'last_month': 'Last Month',
    'this_year': 'This Year',
    'last_year': 'Last Year',
    
    // Common Actions
    'view_all': 'View All',
    'show_more': 'Show More',
    'show_less': 'Show Less',
    'learn_more': 'Learn More',
    'get_started': 'Get Started',
    'try_now': 'Try Now',
    'upgrade': 'Upgrade',
    'downgrade': 'Downgrade',
    'enable': 'Enable',
    'disable': 'Disable',
    'activate': 'Activate',
    'deactivate': 'Deactivate',
    'connect': 'Connect',
    'disconnect': 'Disconnect',
    'sync': 'Sync',
    'backup': 'Backup',
    'restore': 'Restore',
    'export': 'Export',
    'import': 'Import',
    'share': 'Share',
    'print': 'Print',
    'email': 'Email',
    'call': 'Call',
    'message': 'Message',
    'chat': 'Chat',
    'help': 'Help',
    'support': 'Support',
    'contact': 'Contact',
    'about': 'About',
    'terms': 'Terms',
    'privacy': 'Privacy',
    'legal': 'Legal',
    'cookies': 'Cookies',
    
    // Missing Dashboard Translations
    'account_number': 'Account Number',
    'account_id': 'Account ID',
    'total_balance': 'Total Balance',
    'my_accounts': 'My Accounts',
    'verified_account': 'Verified Account',
  },
  zh: {
    // Login Page
    'world_bank': '世界银行',
    'international_banking_solutions': '国际银行解决方案',
    'sign_in': '登录',
    'access_your_secure_banking_portal': '访问您的安全银行门户',
    'email_address': '邮箱地址',
    'user_id_or_email': '用户ID或邮箱',
    'id_placeholder': '输入您的ID或邮箱',
    'password': '密码',
    'login_failed': '登录失败',
    'login_successful': '登录成功',
    'welcome_back': '欢迎回到世界银行',
    'invalid_pin': 'PIN码无效，请重试。',
    'verification_failed': '验证失败，请重试。',
    'enter_pin': '输入PIN码',
    'pin_verification': 'PIN码验证',
    'enter_4_digit_pin': '请输入您的4位PIN码以继续',
    'signing_in': '登录中...',
    'security_center': '安全中心',
    'new_customer': '新客户？',
    'create_account': '创建账户',
    'enter_first_name': '输入您的名字',
    'enter_last_name': '输入您的姓氏',
    'registration_submitted': '注册已提交',
    'admin_review_pending': '您的注册正在等待管理员审核',
    'admin_review_description': '管理员验证后将激活您的账户',
    'next_steps': '下一步',
    'admin_review_process': '管理员将审核您的信息',
    
    // PIN Verification
    'pin_verification_required': '需要PIN验证',
    'enter_pin_complete_login': '输入您的PIN码完成登录',
    'security_pin': '安全PIN码',
    'verify_pin': '验证PIN',

    
    // Form Fields
    'enter_email': '输入您的邮箱地址',
    'enter_phone': '输入您的电话号码',
    'enter_address': '输入您的地址',
    'enter_city': '输入您的城市',
    'enter_state': '输入您的省/州',
    'enter_postal_code': '输入您的邮政编码',
    'enter_profession': '输入您的职业',
    'enter_id_number': '输入您的身份证号',
    'enter_password': '输入您的密码',
    
    // Countries
    'china': '中国',
    'united_states': '美国',
    'united_kingdom': '英国',
    'canada': '加拿大',
    'australia': '澳大利亚',
    'germany': '德国',
    'france': '法国',
    'japan': '日本',
    'other': '其他',
    
    // Income Ranges
    'under_25k': '25,000美元以下',
    '25k_50k': '25,000 - 50,000美元',
    '50k_75k': '50,000 - 75,000美元',
    '75k_100k': '75,000 - 100,000美元',
    '100k_150k': '100,000 - 150,000美元',
    'over_150k': '150,000美元以上',
    
    // ID Types
    'national_id': '身份证',
    'passport': '护照',
    'drivers_license': '驾驶证',
    'email_notification_sent': '将发送邮件通知',
    'account_activation_follows': '随后将激活账户',
    'return_to_login': '返回登录',
    'join_world_bank_today': '立即加入世界银行',
    'personal_information': '个人信息',
    'privacy_policy': '隐私政策',
    'contact_support': '联系支持',
    'copyright_notice': '© 2024 世界银行集团。版权所有。',
    'secure_trusted_global': '安全 • 可信 • 全球',
    'licensed_regulated': '持牌监管金融机构',
    'international_transfer_desc': '向全球190+国家汇款',
    'domestic_transfer_desc': '国内即时转账',
    'card_transfer_desc': '全球借记卡/信用卡转账',
    'mobile_money_desc': '50+国家移动钱包转账',
    'phone_number': '电话号码',
    'address_information': '地址信息',
    'street_address': '街道地址',
    'city': '城市',
    'state_province': '州/省',
    'postal_code': '邮政编码',
    'country': '国家',
    'select_country': '选择国家',
    'professional_information': '职业信息',
    'profession': '职业',
    'annual_income': '年收入',
    'select_income_range': '选择收入范围',
    'identification': '身份证明',
    'id_type': '证件类型',
    'select_id_type': '选择证件类型',
    'id_number': '证件号码',
    'account_security': '账户安全',
    'confirm_password': '确认密码',
    'confirm_your_password': '确认您的密码',
    'already_have_account': '已有账户？',
    'sign_in_here': '点击登录',
    
    // Basic UI
    'welcome': '欢迎',
    'login': '登录',
    'register': '注册',
    'logout': '登出',
    'home': '首页',
    'dashboard': '仪表板',
    'settings': '设置',
    'profile': '个人资料',
    'save': '保存',
    'cancel': '取消',
    'edit': '编辑',
    'delete': '删除',
    'close': '关闭',
    'continue': '继续',
    'back': '返回',
    'next': '下一步',
    'submit': '提交',
    'confirm': '确认',
    'yes': '是',
    'no': '否',
    'loading': '加载中...',
    'error': '错误',
    'success': '成功',
    'warning': '警告',
    'info': '信息',
    'search': '搜索',
    'filter': '筛选',
    'sort': '排序',
    'view': '查看',
    'download': '下载',
    'upload': '上传',
    'copy': '复制',
    'paste': '粘贴',
    'cut': '剪切',
    'undo': '撤销',
    'redo': '重做',
    'refresh': '刷新',
    'update': '更新',
    'create': '创建',
    'new': '新建',
    'open': '打开',
    'select': '选择',
    'choose': '选择',
    'browse': '浏览',
    'clear': '清除',
    'reset': '重置',
    
    // Navigation
    'nav_home': '首页',
    'nav_cards': '卡片',
    'nav_transfer': '转账',
    'nav_history': '历史',
    'nav_profile': '个人',
    
    // Account Preferences
    'account_preferences': '账户偏好设置',
    'manage_account_settings': '管理您的账户设置和偏好',
    'notification_preferences': '通知偏好',
    'email_notifications': '邮件通知',
    'sms_notifications': '短信通知',
    'push_notifications': '推送通知',
    'marketing_notifications': '营销推广',
    'privacy_settings': '隐私设置',
    'share_data': '与合作伙伴共享数据',
    'two_factor_auth': '双重身份验证',
    'display_preferences': '显示偏好',
    'preferred_currency': '首选货币',
    'language': '语言',
    'theme': '主题',
    'security_settings': '安全设置',
    'session_timeout': '会话超时（分钟）',
    'biometric_auth': '生物识别认证',
    'auto_logout': '自动登出',
    'save_preferences': '保存偏好设置',
    
    // Verification Center
    'verification_center': '验证中心',
    'manage_account_verification_status': '管理您的账户验证状态和合规要求',
    'identity_verification': '身份验证',
    'verify_government_id': '验证您的政府颁发身份证件',
    'email_verification': '邮箱验证',
    'confirm_email_address': '确认您的邮箱地址',
    'phone_verification': '手机验证',
    'verify_phone_number': '验证您的手机号码',
    'address_verification': '地址验证',
    'confirm_residential_address': '确认您的居住地址',
    'income_verification': '收入验证',
    'verify_income_employment': '验证您的收入和就业状态',
    'enhanced_due_diligence': '增强尽职调查',
    'additional_verification_high_value': '高价值交易的额外验证',
    'biometric_verification': '生物识别验证',
    'fingerprint_facial_recognition': '指纹和面部识别设置',
    'tax_compliance': '税务合规',
    'tax_residency_status': '税务居住状态和合规验证',
    'account_security_level': '账户安全级别',
    'fully_verified': '完全验证',
    'total_verifications': '总验证项目',
    'verified': '已验证',
    'pending': '待处理',
    'required': '必需',
    'action_required': '需要操作',
    'all_verifications': '所有验证',
    'submitted_documents': '已提交文件',
    'last_updated': '最后更新',
    'upload_documents': '上传文件',
    'under_review': '审核中',
    'upload_verification_documents': '上传验证文件',
    'drag_drop_files_here': '拖拽文件到这里',
    'or_click_to_browse': '或点击浏览',
    'select_files': '选择文件',
    'accepted_formats': '接受的格式',
    'max_file_size': '最大文件大小',
    
    // Banking
    'balance': '余额',
    'account': '账户',
    'transaction': '交易',
    'transfer': '转账',
    'send_money': '发送资金',
    'receive_money': '接收资金',
    'cards': '卡片',
    'history': '历史记录',
    'statements': '对账单',
    'deposits': '存款',
    'withdrawals': '取款',
    'payments': '付款',
    'bills': '账单',
    'loans': '贷款',
    'investments': '投资',
    'insurance': '保险',
    'services': '服务',
    
    // Account Management
    'account_management': '账户管理',
    'account_settings': '账户设置',
    'linked_accounts': '关联账户',
    
    // Banking Services
    'banking_services': '银行服务',
    'loans_credit': '贷款与信贷',
    'foreign_exchange': '外汇',
    'business_banking': '企业银行',
    'wealth_management': '财富管理',
    'international_banking': '国际银行',
    'trade_finance': '贸易金融',
    'cash_management': '现金管理',
    
    // Investment & Wealth
    'investment_wealth': '投资与财富',
    'portfolio_management': '投资组合管理',
    'retirement_planning': '退休规划',
    'financial_advisory': '财务咨询',
    'market_research': '市场研究',
    'investment_products': '投资产品',
    
    // Digital Services
    'digital_services': '数字服务',
    'mobile_banking': '手机银行',
    'online_banking': '网上银行',
    'digital_wallet': '数字钱包',
    'contactless_payments': '非接触式支付',
    'biometric_login': '生物识别登录',
    
    // Support & Help
    'support_help': '支持与帮助',
    'customer_service': '客户服务',
    'live_chat': '在线聊天',
    'help_center': '帮助中心',
    'faqs': '常见问题',
    'contact_us': '联系我们',
    'feedback': '反馈',
    'complaints': '投诉',
    
    // Status
    'active': '活跃',
    'inactive': '非活跃',
    'approved': '已批准',
    'rejected': '已拒绝',
    'processing': '处理中',
    'failed': '失败',
    'completed': '已完成',
    'complete': '完成',
    
    // Transfer Process
    'enter_transfer_pin_to_continue': '请输入转账PIN码以继续',
    'transfer_details': '转账详情',
    'transfer_pin': '转账PIN',
    'verify_and_continue': '验证并继续',
    'processing_transfer': '正在处理转账',
    'please_wait_processing': '请稍候，我们正在处理您的转账...',
    'transaction_id': '交易编号',
    'transfer_submitted': '转账已提交',
    'transfer_being_processed': '您的转账正在处理中',
    'transfer_details_verified': '转账详情已验证',
    'pin_authenticated': 'PIN验证成功',
    'awaiting_final_processing': '等待最终处理',
    'processing_time_notice': '国际转账可能需要1-3个工作日',
    'return_to_dashboard': '返回仪表板',
    'verify': '验证',
    'process': '处理',
    
    // Quick Actions
    'quick_actions': '快速操作',
    'add_money': '充值',
    'alerts': '提醒',
    'notifications': '通知',
    
    // Transfer Types
    'international_transfer': '国际转账',
    'domestic_transfer': '国内转账',
    'card_transfer': '银行卡转账',
    'mobile_money': '手机支付',
    'international_transfer_title': '以优惠汇率向全球汇款',
    'domestic_transfer_title': '国内快速转账',
    'card_transfer_title': '直接转账至借记卡/信用卡',
    'mobile_money_title': '发送至190多个国家的手机钱包',
    'same_day': '当日到账',
    'instant': '即时到账',
    'minutes_to_hours': '1-3小时',
    
    // User Profile
    'mr_liu_wei': '刘伟先生',
    'marine_engineer': '海洋工程师',
    'oil_rig_company': '石油钻井公司',
    'online': '在线',
    'authenticated': '已认证',
    
    // Timing
    'today': '今天',
    'yesterday': '昨天',
    'this_week': '本周',
    'this_month': '本月',
    'last_month': '上月',
    'this_year': '今年',
    'last_year': '去年',
    
    // Common Actions
    'view_all': '查看全部',
    'show_more': '显示更多',
    'show_less': '显示更少',
    'learn_more': '了解更多',
    'get_started': '开始使用',
    'try_now': '立即尝试',
    'upgrade': '升级',
    'downgrade': '降级',
    'enable': '启用',
    'disable': '禁用',
    'activate': '激活',
    'deactivate': '停用',
    'connect': '连接',
    'disconnect': '断开',
    'sync': '同步',
    'backup': '备份',
    'restore': '恢复',
    'export': '导出',
    'import': '导入',
    'share': '分享',
    'print': '打印',
    'email': '邮件',
    'call': '电话',
    'message': '信息',
    'chat': '聊天',
    'help': '帮助',
    'support': '支持',
    'contact': '联系',
    'about': '关于',
    'terms': '条款',
    'privacy': '隐私',
    'legal': '法律',
    'cookies': 'Cookie',
    
    // Missing Dashboard Translations
    'account_number': '账户号码',
    'account_id': '账户ID',
    'total_balance': '总余额',
    'my_accounts': '我的账户',
    'verified_account': '已验证账户',
    
    // PIN Management - Chinese
    'change_transfer_pin': '更改转账PIN码',
    'pin_security_description': '管理您的4位数转账PIN码以确保交易安全',
    'current_pin': '当前PIN码',
    'enter_current_pin': '输入您当前的4位PIN码',
    'new_pin': '新PIN码',
    'enter_new_pin': '输入您的新4位PIN码',
    'confirm_new_pin': '确认新PIN码',
    'pin_security_tips': 'PIN码安全提示',
    'pin_tip_1': '使用独特的4位数字组合',
    'pin_tip_2': '避免连续数字 (1234, 5678)',
    'pin_tip_3': '避免重复数字 (1111, 2222)',
    'pin_tip_4': '保持您的PIN码机密',
    'change_pin': '更改PIN码',
    'pin_too_short': 'PIN码必须是4位数字',
    'confirm_pin_change': '确认PIN码更改',
    'pin_change_confirmation_message': '您确定要更改您的转账PIN码吗？',
    'confirm_change': '确认更改',
    
    // Missing translations - Chinese
    'personal_banking': '个人银行',
    'investment_services': '投资服务',
    'copyright': '版权',
    'terms_of_service': '服务条款',
    'my_cards': '我的卡片',
    'manage_cards': '管理您的信用卡和借记卡',
    'add_card': '添加卡片',
    'view_details': '查看详情',
    'manage': '管理',
    'instant_payments': '即时支付',
    'instant_payments_desc': '全球即时支付',
    'secure_transactions': '安全交易',
    'secure_transactions_desc': '银行级交易安全',
    'mobile_wallet': '移动钱包',
    'mobile_wallet_desc': '使用手机进行非接触式支付',
    'hide_balances': '隐藏余额',
    'show_balances': '显示余额',
    'lock_card': '锁定卡片',
    'unlock_card': '解锁卡片',
    'mobile_pay': '手机支付',
    'pay_bill': '缴费',
    'card_locked': '卡片已锁定',
    'card_unlocked': '卡片已解锁',
    'card_locked_desc': '您的卡片已为安全起见被锁定',
    'card_unlocked_desc': '您的卡片已成功解锁',
    'lock_card_desc': '输入您的PIN码以锁定此卡片',
    'unlock_card_desc': '输入您的PIN码以解锁此卡片进行交易',
    'mobile_payment_sent': '手机支付已发送',
    'bill_payment_successful': '缴费成功',
    'settings_updated': '设置已更新',
    'card_settings_updated': '您的卡片设置已成功更新',
    'unlock': '解锁',
    'lock': '锁定',
    'phone_number': '手机号码',
    'send_payment': '发送支付',
    'bill_provider': '缴费机构',
    'pay_now': '立即支付',
    'card_settings': '卡片设置',
    'daily_spending_limit': '每日消费限额',
    'contactless_payments': '非接触式支付',
    'card_status': '卡片状态',
    'enabled': '已启用',
    'disabled': '已禁用',
    'locked': '已锁定',
    'active': '活跃',
    'save_changes': '保存更改',
    'sent': '已发送',
    'to': '到',
    'paid': '已支付',
    'payment_failed': '支付失败。请重试。',
    'operation_failed': '操作失败。请重试。',
    
    // Transfer Process
    'verify_transfer_pin': '验证转账PIN码',
    'enter_4_digit_pin_to_authorize': '输入您的4位PIN码以授权此转账',

    'transfer_failed_try_again': '转账失败。请重试。',
    'processing_your_transfer_request': '正在处理您的转账请求...',
    'transfer_pending': '转账待处理',
    'transfer_submitted_for_review': '您的转账已提交审核',
    'awaiting_processing': '等待处理',
    'transfer_id': '转账ID',
    'amount': '金额',
    'recipient': '收款人',
    'bank': '银行',
    'admin_will_review_shortly': '我们的团队将很快审核并处理您的转账。',
  }
};

const LanguageContext = createContext<LanguageContextType | null>(null);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [currentLanguage, setCurrentLanguage] = useState<Language>(languages[0]);

  useEffect(() => {
    const savedLanguage = localStorage.getItem('preferred-language');
    if (savedLanguage) {
      const language = languages.find(lang => lang.code === savedLanguage);
      if (language) {
        setCurrentLanguage(language);
      }
    }
  }, []);

  const setLanguage = (language: Language) => {
    setCurrentLanguage(language);
    localStorage.setItem('preferred-language', language.code);
  };

  const t = (key: string): string => {
    try {
      // Get current language code safely
      const langCode = currentLanguage?.code || 'en';
      
      // Get translations for current language with fallback to English
      const currentTranslations = translations[langCode] || translations['en'];
      
      if (!currentTranslations) {
        // console.warn(`No translations found for language: ${langCode}`);
        return key;
      }
      
      // Get translation with fallback to English if not found in current language
      let translation = currentTranslations[key];
      
      if (!translation && langCode !== 'en') {
        translation = translations['en']?.[key];
      }
      
      if (!translation) {
        // console.warn(`Missing translation for key: ${key} in both ${langCode} and English`);
        return key;
      }
      
      return translation;
    } catch (error) {
      // console.error(`Translation error for key: ${key}`, error);
      return key;
    }
  };

  return (
    <LanguageContext.Provider value={{ 
      currentLanguage, 
      setLanguage, 
      languages, 
      t 
    }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}