import { useState, createContext, ReactNode, useContext } from "react";

type Language = 'en' | 'zh';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    // Login & Auth
    'world_bank': 'WORLD BANK',
    'international_banking_solutions': 'International Banking Solutions',
    'sign_in': 'Sign In',
    'access_your_secure_banking_portal': 'Access your secure banking portal',
    'email_address': 'Email Address',
    'user_id_or_email': 'User ID or Email',
    'id_placeholder': 'Enter your ID or email',
    'password': 'Password',
    'enter_password': 'Enter your password',
    'login_failed': 'Login Failed',
    'login_successful': 'Login Successful',
    'welcome_back': 'Welcome back to World Bank',
    'invalid_pin': 'Invalid PIN. Please try again.',
    'verification_failed': 'Verification failed. Please try again.',
    'enter_pin': 'Enter PIN',
    'pin_verification': 'PIN Verification',
    'enter_4_digit_pin': 'Enter your 4-digit PIN to continue',
    'signing_in': 'Signing In...',
    'security_center': 'Security Center',
    'new_customer': 'New customer?',
    'create_account': 'Create Account',

    // Dashboard
    'dashboard': 'Dashboard',
    'dashboard.title': 'Dashboard',
    'dashboard.balance': 'Total Balance',
    'dashboard.available': 'Available Balance',
    'dashboard.pending': 'Pending Transactions',
    'dashboard.accounts': 'My Accounts',
    'dashboard.recent': 'Recent Transactions',
    'dashboard.transfer': 'Transfer',
    'dashboard.deposit': 'Deposit',
    'dashboard.withdraw': 'Withdraw',
    'dashboard.pay': 'Pay Bills',
    'balance': 'Balance',
    'account': 'Account',
    'total_balance': 'Total Balance',
    'available_balance': 'Available Balance',
    'quick_actions': 'Quick Actions',
    'send_money': 'Send Money',
    'add_money': 'Add Money',
    'pay_bill': 'Pay Bill',
    'recent_activity': 'Recent Activity',
    'view_all': 'View All',

    // Transfer
    'transfer': 'Transfer',
    'transfer.title': 'Transfer Money',
    'transfer.amount': 'Amount',
    'transfer.recipient': 'Recipient',
    'transfer.account': 'Account Number',
    'transfer.submit': 'Send Transfer',
    'transfer.processing': 'Processing',
    'transfer.success': 'Transfer Successful',
    'international_transfer': 'International Transfer',
    'international_transfer_title': 'International Wire Transfer', 
    'international_transfer_desc': 'SWIFT Network • Bank Grade Security • Global Coverage',
    'domestic_transfer': 'Domestic Transfer',
    'domestic_transfer_title': 'Domestic Transfer',
    'domestic_transfer_desc': 'Instant delivery • No fees • 24/7 service',
    'card_transfer_title': 'Card Transfer',
    'card_transfer_desc': 'Debit/Credit cards • Instant delivery',
    'mobile_money_title': 'Mobile Money', 
    'mobile_money_desc': 'Fast & convenient • Mobile wallets',
    'same_day': 'Same day',
    'instant': 'Instant',
    'minutes_to_hours': 'Minutes to hours',
    'account_number': 'Account Number',
    'account_id': 'Account ID',
    'my_accounts': 'My Accounts',
    'amount': 'Amount',
    'recipient': 'Recipient',
    'welcome': 'Welcome to World Bank Digital Services',
    'available': 'Available Balance',
    'checking_account': 'Primary Checking Account',
    'savings_account': 'High-Yield Savings Account', 
    'investment_account': 'Investment Portfolio Account',
    'send_money_worldwide': 'International Wire Transfer Services',
    'request_money': 'Payment Request Service',
    'fund_account': 'Account Funding Options',
    'customer_support': 'Premium Customer Support',
    'banking_alerts': 'Security & Transaction Alerts',
    'new_notifications': 'unread notifications',
    'download_reports': 'Financial Statement Download',
    'currency_rates': 'Real-Time Exchange Rates',
    'portfolio_view': 'Investment Portfolio Analysis',
    'recent_transactions': 'Transaction History',
    'salary_payment': 'Salary Direct Deposit',
    'grocery_store': 'Retail Purchase Transaction',
    'investment_return': 'Investment Portfolio Return',
    'processing': 'Transaction Processing',
    'completed': 'Successfully Completed',
    'pending': 'Awaiting Approval',
    'failed': 'Transaction Declined',

    // Navigation
    'nav.home': 'Home',
    'nav.transfer': 'Transfer',
    'nav.cards': 'Cards',
    'nav.profile': 'Profile',
    'nav.support': 'Support',
    'home': 'Home',
    'cards': 'Cards',
    'profile': 'Profile',
    'support': 'Support',
    'history': 'History',

    // Cards
    'my_cards': 'My Cards',
    'manage_cards': 'Manage your credit and debit cards',
    'add_card': 'Add Card',
    'card_settings': 'Card Settings',
    'lock_card': 'Lock Card',
    'unlock_card': 'Unlock Card',
    'view_details': 'View Details',
    'manage': 'Manage',

    // Common
    'loading': 'Loading...',
    'common.loading': 'Loading...',
    'pin_verification_required': 'PIN Verification Required',
    'enter_pin_complete_login': 'Enter your PIN to complete login',
    'security_pin': 'Security PIN',
    'cancel': 'Cancel',
    'verify_pin': 'Verify PIN',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'common.close': 'Close',
    'common.save': 'Save',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'save': 'Save',
    'edit': 'Edit',
    'delete': 'Delete',
    'close': 'Close',
    'confirm': 'Confirm',
    'continue': 'Continue',
    'back': 'Back',
    'next': 'Next',
    'submit': 'Submit',
    'error': 'Error',
    'success': 'Success',
    'warning': 'Warning',
    'info': 'Information',

    // International Banking
    'international_banking': 'International Banking',
    'international_transfers': 'International Transfers',
    'currency_exchange': 'Currency Exchange',
    'cross_border_payments': 'Cross-Border Payments',
    'swift_transfers': 'SWIFT Transfers',
    'correspondent_banking': 'Correspondent Banking',
    'foreign_exchange': 'Foreign Exchange',
    'trade_finance': 'Trade Finance',
    'letter_of_credit': 'Letter of Credit',
    'wire_transfers': 'Wire Transfers',
    'multi_currency_accounts': 'Multi-Currency Accounts',
    'exchange_rates': 'Exchange Rates',
    'international_compliance': 'International Compliance',
    'anti_money_laundering': 'Anti-Money Laundering (AML)',
    'know_your_customer': 'Know Your Customer (KYC)',
    'sanctions_screening': 'Sanctions Screening',
    'regulatory_reporting': 'Regulatory Reporting',

    // Account & Profile
    'verified_account': 'Verified Account',
    'account_preferences': 'Account Preferences',
    'manage_account_settings': 'Manage your account settings and preferences',
    'notification_preferences': 'Notification Preferences',
    'email_notifications': 'Email Notifications',
    'sms_notifications': 'SMS Notifications',
    'push_notifications': 'Push Notifications',
    'privacy_settings': 'Privacy Settings',
    'show_balance': 'Show Balance',
    'two_factor_auth': 'Two-Factor Authentication',
    'display_preferences': 'Display Preferences',
    'preferred_currency': 'Preferred Currency',
    'language': 'Language',
    'security_settings': 'Security Settings',
    'session_timeout': 'Session Timeout',
    'biometric_auth': 'Biometric Authentication',
    'save_preferences': 'Save Preferences',
    'phone': 'Phone Number',
    'profession': 'Profession',
    'online': 'Online',
    'authenticated': 'Authenticated',
    'no_credit_cards': 'No Credit Cards',
    'you_dont_have_any_credit_cards_yet': "You don't have any credit cards yet.",
    'apply_for_card': 'Apply for Card',
    'mobile_pay': 'Mobile Pay',
    'no_recent_transactions_available': 'No recent transactions available',
    'prof': 'Profile',
    'receive': 'Receive',
    'live_chat': 'Live Chat',
    'statements': 'Statements',
    'exchange': 'Exchange',
    'investments': 'Investments',
    'vs_last_month': 'vs last month',
    'processing_transfer': 'Processing transfer',
    'send_amount': 'Send Amount',
    'profile_settings': 'Profile Settings',
    'view_your_profile_information_and_account_details': 'View your profile information and account details',
    'profile_information': 'Profile Information',
    'secure_profile': 'Secure Profile',
    'address_information': 'Address Information',
    'address': 'Address',
    'postal_code': 'Postal Code',
    'transfer_pin_settings': 'Transfer PIN Settings',
    'contact_customer_support_to_request_pin_changes': 'Contact customer support to request PIN changes',
    'admin_only': 'Admin Only',
    'admin_will_review_shortly': 'Our customer support team will review your request shortly',
    'two_factor_authentication': 'Two-Factor Authentication',
    'add_an_extra_layer_of_security': 'Add an extra layer of security',
    'enabled': 'Enabled',
    'session_security': 'Session Security',
    'automatic_logout_and_session_management': 'Automatic logout and session management',
    'active': 'Active',
    'account_actions': 'Account Actions',
    'verification_center': 'Verification Center',
    'need_to_update_your_profile_information': 'Need to update your profile information? Contact our customer support team for assistance.',
    'contact_support': 'Contact Support',
    'full_name': 'Full Name',
    'nationality': 'Nationality',
    'annual_income': 'Annual Income',

    // Verification Center
    'identity_verification': 'Identity Verification',
    'government_issued_id_verification': 'Government-issued ID verification',
    'submitted_documents': 'Submitted Documents',
    'last_updated': 'Last Updated',
    'email_verification': 'Email Verification',
    'confirm_email_address': 'Confirm your email address',
    'phone_verification': 'Phone Verification',
    'verify_mobile_number': 'Verify your mobile number',
    'address_verification': 'Address Verification',
    'proof_of_residence_verification': 'Proof of residence verification',
    'income_verification': 'Income Verification',
    'employment_and_income_proof': 'Employment and income proof',
    'enhanced_due_diligence': 'Enhanced Due Diligence',
    'additional_verification_high_value': 'Additional verification for high-value transactions',
    'biometric_verification': 'Biometric Verification',
    'facial_recognition_fingerprint': 'Facial recognition and fingerprint',
    'tax_compliance': 'Tax Compliance',
    'tax_residency_status': 'Tax residency status verification',
    'under_review': 'Under Review',
    'upload_documents': 'Upload Documents',
    'regulatory_compliance': 'Regulatory Compliance',
    'verification_compliance_description': 'World Bank adheres to international banking regulations and compliance standards',
    'know_your_customer_kyc': 'Know Your Customer (KYC)',
    'anti_money_laundering_aml': 'Anti-Money Laundering (AML)',
    'combating_financing_terrorism_cft': 'Combating the Financing of Terrorism (CFT)',
    'international_banking_regulations': 'International Banking Regulations',
    'manage_account_verification_status': 'Manage your account verification status and documents',
    'account_security_level': 'Account Security Level',
    'fully_verified': 'Fully Verified',
    'total_verifications': 'Total Verifications',
    'verified': 'Verified',
    'awaiting_approval': 'Awaiting Approval',
    'action_required': 'Action Required',
    'all_verifications': 'All Verifications',

    // Investment
    'investment_portfolio': 'Investment Portfolio',
    'manage_investments': 'Manage your investments and track performance',
    'invest_now': 'Invest Now',
    'total_portfolio_value': 'Total Portfolio Value',
    'last_30_days': 'Last 30 Days',
    'market_overview': 'Market Overview',
    'stocks': 'Stocks',
    'bonds': 'Bonds',
    'crypto': 'Cryptocurrency',
    'forex': 'Forex',
    'investment_actions': 'Investment Actions',
    'buy_stocks': 'Buy Stocks',
    'portfolio_review': 'Portfolio Review',
    'market_analysis': 'Market Analysis',
    'rebalance': 'Rebalance',

    // Support
    'help_center': 'Help Center',
    'contact_us': 'Contact Us',
    'privacy_policy': 'Privacy Policy',
    'copyright': '© 2025 World Bank',
    'terms_of_service': 'Terms of Service',
    'connect': 'Connect With Us',
    'secure_trusted_global': 'Secure • Trusted • Global',
    'banking_services': 'Banking Services',
    'personal_banking': 'Personal Banking',
    'business_banking': 'Business Banking',
    'investment_services': 'Investment Services',
    'loans_credit': 'Loans & Credit',
    'submit_support_request': 'Submit Support Request',
    'subject': 'Subject',
    'category': 'Category',
    'select_issue_category': 'Select issue category',
    'priority': 'Priority',
    'select_priority_level': 'Select priority level',
    'description': 'Description',
    'submit_request': 'Submit Request',
    'contact_information': 'Contact Information',
    'phone_support': 'Phone Support',
    'email_support': 'Email Support',
    'response_within_24_hours': 'Response within 24 hours',
    'emergency_services': 'Emergency Services',
    'report_lost_stolen_card': 'Report Lost/Stolen Card',
    'dispute_transaction': 'Dispute Transaction',
    'freeze_account': 'Freeze Account',
    'submit_support_ticket': 'Submit Support Ticket',
    'exchange_page_not_found': 'Exchange Page Not Found',
    'the_exchange_page_is_currently_unavailable': 'The exchange page is currently unavailable. Please try again later.',
    'go_to_dashboard': 'Go to Dashboard',
    'support_ticket_submission_failed': 'Support Ticket Submission Failed',
    'your_support_ticket_could_not_be_submitted': 'Your support ticket could not be submitted. Please try again or contact us directly.',
    'checking_accounts': 'Checking Accounts',
    'checking_description': 'Secure checking accounts with competitive rates',
    'no_minimum_balance': 'No Minimum Balance',
    'free_atm_worldwide': 'Free ATM Worldwide',
    'mobile_banking': 'Mobile Banking',
    'savings_accounts': 'Savings Accounts',
    'savings_description': 'High-yield savings accounts with great rates',
    'high_apy': 'High APY',
    'no_monthly_fees': 'No Monthly Fees',
    'automatic_savings': 'Automatic Savings',
    'credit_cards': 'Credit Cards',
    'credit_cards_description': 'Premium credit cards with exclusive benefits',
    'no_foreign_fees': 'No Foreign Fees',
    'travel_rewards': 'Travel Rewards',
    'purchase_protection': 'Purchase Protection',
    'mortgage_services': 'Mortgage Services',
    'mortgage_description': 'Competitive mortgage rates for your dream home',
    'competitive_rates': 'Competitive Rates',
    'multiple_currencies': 'Multiple Currencies',
    'expert_guidance': 'Expert Guidance',
    'business_banking_description': 'Complete business banking solutions for growth',
    'multi_currency_accounts': 'Multi-Currency Accounts',
    'trade_finance': 'Trade Finance',
    'cash_management': 'Cash Management',
    'international_trade': 'International Trade',
    'international_trade_description': 'Global trade services and solutions',
    'letters_of_credit': 'Letters of Credit',
    'documentary_collections': 'Documentary Collections',
    'trade_guarantees': 'Trade Guarantees',
    'investment_services_description': 'Professional investment management',
    'portfolio_management': 'Portfolio Management',
    'market_research': 'Market Research',
    'risk_assessment': 'Risk Assessment',
    'treasury_services_description': 'Corporate treasury and payment solutions',
    'liquidity_management': 'Liquidity Management',
    'fx_services': 'FX Services',
    'payment_solutions': 'Payment Solutions',
    'loan_services_description': 'Flexible lending options',
    'personal_loans': 'Personal Loans',
    'auto_loans': 'Auto Loans',
    'business_loans': 'Business Loans',
    'equipment_financing': 'Equipment Financing',
    'education_financing_description': 'Education financing for your future',
    'student_loans': 'Student Loans',
    'education_savings': 'Education Savings',
    'study_abroad_financing': 'Study Abroad Financing',
    'insurance_services_description': 'Comprehensive insurance products',
    'life_insurance': 'Life Insurance',
    'property_insurance': 'Property Insurance',
    'business_insurance': 'Business Insurance',
    'specialty_services': 'Specialty Services',
    'global_infrastructure': 'Global Infrastructure',
    'learn_more': 'Learn More',
    'explore_options': 'Explore Options',
    'comprehensive_solutions': 'Comprehensive financial solutions designed for individuals and businesses operating globally'
  },
  zh: {
    // Login & Auth
    'world_bank': '世界银行',
    'international_banking_solutions': '国际银行解决方案',
    'sign_in': '登录',
    'access_your_secure_banking_portal': '访问您的安全银行门户',
    'email_address': '电子邮箱',
    'user_id_or_email': '用户ID或邮箱',
    'id_placeholder': '输入您的ID或邮箱',
    'password': '密码',
    'enter_password': '输入您的密码',
    'login_failed': '登录失败',
    'login_successful': '登录成功',
    'welcome_back': '欢迎回到世界银行',
    'invalid_pin': '无效的PIN。请重试。',
    'verification_failed': '验证失败。请重试。',
    'enter_pin': '输入PIN',
    'pin_verification': 'PIN验证',
    'enter_4_digit_pin': '输入您的4位PIN以继续',
    'signing_in': '登录中...',
    'security_center': '安全中心',
    'new_customer': '新客户？',
    'create_account': '创建账户',

    // Dashboard
    'dashboard': '仪表板',
    'dashboard.title': '仪表板',
    'dashboard.balance': '总余额',
    'dashboard.available': '可用余额',
    'dashboard.pending': '待处理交易',
    'dashboard.accounts': '我的账户',
    'dashboard.recent': '最近交易',
    'dashboard.transfer': '转账',
    'dashboard.deposit': '存款',
    'dashboard.withdraw': '取款',
    'dashboard.pay': '缴费',
    'balance': '余额',
    'account': '账户',
    'available_balance': '可用余额',
    'send_money': '转账',
    'add_money': '存款',
    'pay_bill': '缴费',
    'recent_activity': '最近活动',
    'view_all': '查看全部',

    // Transfer
    'transfer': '转账',
    'transfer.title': '转账',
    'transfer.amount': '金额',
    'transfer.recipient': '收款人',
    'transfer.account': '账号',
    'transfer.submit': '发送转账',
    'transfer.processing': '处理中',
    'transfer.success': '转账成功',
    'international_transfer': '国际转账',
    'domestic_transfer': '国内转账',
    'amount': '金额',
    'recipient': '收款人',
    'processing': '处理中',
    'completed': '已完成',
    'pending': '待处理',
    'failed': '失败',

    // Navigation
    'nav.home': '首页',
    'nav.transfer': '转账',
    'nav.cards': '卡片',
    'nav.profile': '个人资料',
    'nav.support': '客服',
    'home': '首页',
    'cards': '卡片',
    'profile': '个人资料',
    'support': '客服',
    'history': '历史记录',

    // Cards
    'my_cards': '我的卡片',
    'manage_cards': '管理您的信用卡和借记卡',
    'add_card': '添加卡片',
    'card_settings': '卡片设置',
    'lock_card': '锁定卡片',
    'unlock_card': '解锁卡片',
    'view_details': '查看详情',
    'manage': '管理',

    // Common
    'loading': '加载中...',
    'common.loading': '加载中...',
    'common.error': '错误',
    'common.success': '成功',
    'common.cancel': '取消',
    'common.confirm': '确认',
    'common.close': '关闭',
    'common.save': '保存',
    'common.edit': '编辑',
    'common.delete': '删除',
    'save': '保存',
    'cancel': '取消',
    'edit': '编辑',
    'delete': '删除',
    'close': '关闭',
    'confirm': '确认',
    'continue': '继续',
    'back': '返回',
    'next': '下一步',
    'submit': '提交',
    'error': '错误',
    'success': '成功',
    'warning': '警告',
    'info': '信息',

    // International Banking (Chinese)
    'international_banking': '国际银行',
    'international_transfers': '国际转账',
    'currency_exchange': '外汇兑换',
    'cross_border_payments': '跨境支付',
    'swift_transfers': 'SWIFT转账',
    'correspondent_banking': '代理银行',
    'foreign_exchange': '外汇',
    'trade_finance': '贸易融资',
    'letter_of_credit': '信用证',
    'wire_transfers': '电汇',
    'multi_currency_accounts': '多币种账户',
    'exchange_rates': '汇率',
    'international_compliance': '国际合规',
    'anti_money_laundering': '反洗钱 (AML)',
    'know_your_customer': '了解您的客户 (KYC)',
    'sanctions_screening': '制裁筛查',
    'regulatory_reporting': '监管报告',

    // Account & Profile (Chinese)
    'verified_account': '已验证账户',
    'account_preferences': '账户偏好设置',
    'manage_account_settings': '管理您的账户设置和偏好',
    'notification_preferences': '通知偏好',
    'email_notifications': '邮件通知',
    'sms_notifications': '短信通知',
    'push_notifications': '推送通知',
    'privacy_settings': '隐私设置',
    'show_balance': '显示余额',
    'two_factor_auth': '双重身份验证',
    'display_preferences': '显示偏好',
    'preferred_currency': '首选货币',
    'language': '语言',
    'security_settings': '安全设置',
    'session_timeout': '会话超时',
    'biometric_auth': '生物识别认证',
    'save_preferences': '保存偏好设置',
    'phone': '电话号码',
    'profession': '职业',
    'online': '在线',
    'authenticated': '已认证',
    'no_credit_cards': '无信用卡',
    'you_dont_have_any_credit_cards_yet': '您尚未拥有任何信用卡。',
    'apply_for_card': '申请卡片',
    'mobile_pay': '移动支付',
    'no_recent_transactions_available': '暂无最近交易',
    'prof': '个人',
    'receive': '接收',
    'live_chat': '在线客服',
    'statements': '对账单',
    'exchange': '外汇',
    'investments': '投资',
    'vs_last_month': '与上月相比',
    'processing_transfer': '转账处理中',
    'send_amount': '发送金额',
    'profile_settings': '个人资料设置',
    'view_your_profile_information_and_account_details': '查看您的个人资料信息和账户详情',
    'profile_information': '个人信息',
    'secure_profile': '安全资料',
    'address_information': '地址信息',
    'postal_code': '邮政编码',
    'transfer_pin_settings': '转账PIN设置',
    'contact_customer_support_to_request_pin_changes': '联系客户支持请求PIN更改',
    'admin_only': '仅限管理员',
    'two_factor_authentication': '双重身份验证',
    'add_an_extra_layer_of_security': '添加额外的安全层',
    'enabled': '已启用',
    'session_security': '会话安全',
    'automatic_logout_and_session_management': '自动注销和会话管理',
    'active': '活跃',
    'account_actions': '账户操作',
    'verification_center': '验证中心',
    'need_to_update_your_profile_information': '需要更新您的个人资料信息？请联系我们的客户支持团队寻求帮助。',
    'contact_support': '联系支持',
    'full_name': '全名',
    'nationality': '国籍',
    'annual_income': '年收入',

    // Verification Center (Chinese)
    'identity_verification': '身份验证',
    'government_issued_id_verification': '政府签发身份证件验证',
    'submitted_documents': '已提交文件',
    'last_updated': '最后更新',
    'email_verification': '邮箱验证',
    'confirm_email_address': '确认您的邮箱地址',
    'phone_verification': '手机验证',
    'verify_mobile_number': '验证您的手机号码',
    'address_verification': '地址验证',
    'proof_of_residence_verification': '居住证明验证',
    'income_verification': '收入验证',
    'employment_and_income_proof': '就业和收入证明',
    'enhanced_due_diligence': '增强尽职调查',
    'additional_verification_high_value': '高价值交易的额外验证',
    'biometric_verification': '生物识别验证',
    'facial_recognition_fingerprint': '面部识别和指纹',
    'tax_compliance': '税务合规',
    'tax_residency_status': '税务居民身份验证',
    'under_review': '审核中',
    'upload_documents': '上传文件',
    'regulatory_compliance': '监管合规',
    'verification_compliance_description': '世界银行遵守国际银行法规和合规标准',
    'know_your_customer_kyc': '了解您的客户 (KYC)',
    'anti_money_laundering_aml': '反洗钱 (AML)',
    'combating_financing_terrorism_cft': '反恐怖主义融资 (CFT)',
    'international_banking_regulations': '国际银行法规',
    'manage_account_verification_status': '管理您的账户验证状态和文件',
    'account_security_level': '账户安全级别',
    'fully_verified': '完全验证',
    'total_verifications': '总验证次数',
    'verified': '已验证',
    'awaiting_approval': '待批准',
    'action_required': '需要操作',
    'all_verifications': '所有验证',

    // Investment (Chinese)
    'investment_portfolio': '投资组合',
    'manage_investments': '管理您的投资并跟踪绩效',
    'invest_now': '立即投资',
    'total_portfolio_value': '投资组合总价值',
    'last_30_days': '过去30天',
    'market_overview': '市场概览',
    'stocks': '股票',
    'bonds': '债券',
    'crypto': '加密货币',
    'forex': '外汇',
    'investment_actions': '投资操作',
    'buy_stocks': '购买股票',
    'portfolio_review': '投资组合回顾',
    'market_analysis': '市场分析',
    'rebalance': '重新平衡',

    // Support (Chinese)
    'help_center': '帮助中心',
    'contact_us': '联系我们',
    'privacy_policy': '隐私政策',
    'copyright': '© 2025 世界银行',
    'terms_of_service': '服务条款',
    'connect': '与我们联系',
    'secure_trusted_global': '安全 • 可信 • 全球',
    'banking_services': '银行服务',
    'personal_banking': '个人银行业务',
    'business_banking': '企业银行业务',
    'investment_services': '投资服务',
    'loans_credit': '贷款与信贷',
    'submit_support_request': '提交支持请求',
    'subject': '主题',
    'category': '类别',
    'select_issue_category': '选择问题类别',
    'priority': '优先级',
    'select_priority_level': '选择优先级级别',
    'description': '描述',
    'submit_request': '提交请求',
    'contact_information': '联系信息',
    'phone_support': '电话支持',
    'email_support': '邮件支持',
    'response_within_24_hours': '24小时内回复',
    'emergency_services': '紧急服务',
    'report_lost_stolen_card': '报告卡片丢失/被盗',
    'dispute_transaction': '交易争议',
    'freeze_account': '冻结账户',
    'submit_support_ticket': '提交支持工单',
    'exchange_page_not_found': '未找到兑换页面',
    'the_exchange_page_is_currently_unavailable': '兑换页面目前不可用。请稍后再试。',
    'go_to_dashboard': '转到仪表板',
    'support_ticket_submission_failed': '支持工单提交失败',
    'your_support_ticket_could_not_be_submitted': '您的支持工单未能提交。请重试或直接联系我们。',
    'checking_accounts': '支票账户',
    'checking_description': '具有竞争性利率的安全支票账户',
    'no_minimum_balance': '无最低余额',
    'free_atm_worldwide': '全球免费ATM',
    'mobile_banking': '手机银行',
    'savings_accounts': '储蓄账户',
    'savings_description': '高收益储蓄账户，利率优惠',
    'high_apy': '高年利率',
    'no_monthly_fees': '无月费',
    'automatic_savings': '自动转账',
    'credit_cards': '信用卡',
    'credit_cards_description': '带有独家优势的优质信用卡',
    'no_foreign_fees': '无外币费用',
    'travel_rewards': '旅游奖励',
    'purchase_protection': '购物保护',
    'mortgage_services': '抵押服务',
    'mortgage_description': '为您的梦想家园提供竞争性抵押利率',
    'competitive_rates': '竞争性利率',
    'multiple_currencies': '多种货币',
    'expert_guidance': '专家指导',
    'business_banking_description': '完整的业务银行解决方案，助力增长',
    'multi_currency_accounts': '多币种账户',
    'trade_finance': '贸易融资',
    'cash_management': '现金管理',
    'international_trade': '国际贸易',
    'international_trade_description': '全球贸易服务和解决方案',
    'letters_of_credit': '信用证',
    'documentary_collections': '单据托收',
    'trade_guarantees': '贸易担保',
    'investment_services_description': '专业投资管理',
    'portfolio_management': '投资组合管理',
    'market_research': '市场研究',
    'risk_assessment': '风险评估',
    'treasury_services_description': '公司资金库和支付解决方案',
    'liquidity_management': '流动性管理',
    'fx_services': '外汇服务',
    'payment_solutions': '支付解决方案',
    'loan_services_description': '灵活的贷款选项',
    'personal_loans': '个人贷款',
    'auto_loans': '汽车贷款',
    'business_loans': '商业贷款',
    'equipment_financing': '设备融资',
    'education_financing_description': '为您的未来提供教育融资',
    'student_loans': '学生贷款',
    'education_savings': '教育储蓄',
    'study_abroad_financing': '出国留学融资',
    'insurance_services_description': '全面的保险产品',
    'life_insurance': '人寿保险',
    'property_insurance': '财产保险',
    'business_insurance': '商业保险',
    'specialty_services': '专业服务',
    'global_infrastructure': '全球基础设施',
    'learn_more': '了解更多',
    'explore_options': '探索选项',
    'comprehensive_solutions': '为在全球范围内开展业务的个人和企业设计的全面金融解决方案'
  }
};

const LanguageContext = createContext<LanguageContextType | null>(null);

// Auto-detect user's region and language
function detectUserLanguage(): Language {
  // Check URL parameter first
  const urlParams = new URLSearchParams(window.location.search);
  const urlLang = urlParams.get('lang');
  if (urlLang === 'zh' || urlLang === 'en') {
    return urlLang as Language;
  }

  // Check localStorage
  const savedLang = localStorage.getItem('worldbank_language');
  if (savedLang === 'zh' || savedLang === 'en') {
    return savedLang as Language;
  }

  // Auto-detect based on browser/timezone/IP
  const browserLang = navigator.language.toLowerCase();
  const timezone = Intl.DateTimeFormat().resolvedOptions().timeZone;

  // China regions and Chinese language detection
  if (browserLang.includes('zh') || 
      timezone.includes('Shanghai') || 
      timezone.includes('Beijing') || 
      timezone.includes('Chongqing') ||
      timezone.includes('Hong_Kong') ||
      timezone.includes('Macau') ||
      timezone.includes('Asia/Shanghai') ||
      timezone.includes('Asia/Hong_Kong')) {
    return 'zh';
  }

  // Default to English for other regions
  return 'en';
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => detectUserLanguage());

  const changeLanguage = (newLang: Language) => {
    setLanguage(newLang);
  };

  const t = (key: string): string => {
    return (translations[language] as any)[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}